// Generated by gencpp from file esp32_msgs/Esp32Data.msg
// DO NOT EDIT!


#ifndef ESP32_MSGS_MESSAGE_ESP32DATA_H
#define ESP32_MSGS_MESSAGE_ESP32DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace esp32_msgs
{
template <class ContainerAllocator>
struct Esp32Data_
{
  typedef Esp32Data_<ContainerAllocator> Type;

  Esp32Data_()
    : v1(0)
    , v2(0)
    , v3(0)
    , v4(0)
    , v5(0)  {
    }
  Esp32Data_(const ContainerAllocator& _alloc)
    : v1(0)
    , v2(0)
    , v3(0)
    , v4(0)
    , v5(0)  {
  (void)_alloc;
    }



   typedef int32_t _v1_type;
  _v1_type v1;

   typedef int32_t _v2_type;
  _v2_type v2;

   typedef int32_t _v3_type;
  _v3_type v3;

   typedef int32_t _v4_type;
  _v4_type v4;

   typedef int32_t _v5_type;
  _v5_type v5;





  typedef boost::shared_ptr< ::esp32_msgs::Esp32Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esp32_msgs::Esp32Data_<ContainerAllocator> const> ConstPtr;

}; // struct Esp32Data_

typedef ::esp32_msgs::Esp32Data_<std::allocator<void> > Esp32Data;

typedef boost::shared_ptr< ::esp32_msgs::Esp32Data > Esp32DataPtr;
typedef boost::shared_ptr< ::esp32_msgs::Esp32Data const> Esp32DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esp32_msgs::Esp32Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esp32_msgs::Esp32Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::esp32_msgs::Esp32Data_<ContainerAllocator1> & lhs, const ::esp32_msgs::Esp32Data_<ContainerAllocator2> & rhs)
{
  return lhs.v1 == rhs.v1 &&
    lhs.v2 == rhs.v2 &&
    lhs.v3 == rhs.v3 &&
    lhs.v4 == rhs.v4 &&
    lhs.v5 == rhs.v5;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::esp32_msgs::Esp32Data_<ContainerAllocator1> & lhs, const ::esp32_msgs::Esp32Data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace esp32_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::esp32_msgs::Esp32Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_msgs::Esp32Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esp32_msgs::Esp32Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esp32_msgs::Esp32Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_msgs::Esp32Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_msgs::Esp32Data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esp32_msgs::Esp32Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a281a2c1c2d8004205b58477743bf196";
  }

  static const char* value(const ::esp32_msgs::Esp32Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa281a2c1c2d80042ULL;
  static const uint64_t static_value2 = 0x05b58477743bf196ULL;
};

template<class ContainerAllocator>
struct DataType< ::esp32_msgs::Esp32Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esp32_msgs/Esp32Data";
  }

  static const char* value(const ::esp32_msgs::Esp32Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esp32_msgs::Esp32Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 v1\n"
"int32 v2\n"
"int32 v3\n"
"int32 v4\n"
"int32 v5\n"
;
  }

  static const char* value(const ::esp32_msgs::Esp32Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esp32_msgs::Esp32Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v1);
      stream.next(m.v2);
      stream.next(m.v3);
      stream.next(m.v4);
      stream.next(m.v5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Esp32Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esp32_msgs::Esp32Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::esp32_msgs::Esp32Data_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "v1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v5: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESP32_MSGS_MESSAGE_ESP32DATA_H
